package drools.spring.rules;

import rs.ac.uns.ftn.backend.model.Rating;

/*can not operate with null values*/

rule "Set frequency1 to 0"
	salience 100
    when
        $rating: Rating(frequency1 == null)
    then
    	// Set frequency1 to 0
    	modify($rating) { 
    		 setFrequency1(0);
    	}    
end

rule "Set frequency2 to 0"
	salience 100
    when
        $rating: Rating(frequency2 == null)
    then
    	// Set frequency2 to 0
    	modify($rating) { 
    		 setFrequency2(0);
    	}    
end

rule "Set frequency3 to 0"
	salience 100
    when
        $rating: Rating(frequency3 == null)
    then
    	// Set frequency3 to 0
    	modify($rating) { 
    		 setFrequency3(0);
    	}    
end

rule "Set frequency4 to 0"
	salience 100
    when
        $rating: Rating(frequency4 == null)
    then
    	// Set frequency4 to 0
    	modify($rating) { 
    		 setFrequency4(0);
    	}    
end

rule "Set frequency5 to 0"
	salience 100
    when
        $rating: Rating(frequency5 == null)
    then
    	// Set frequency5 to 0
    	modify($rating) { 
    		 setFrequency5(0);
    	}    
end

/*must cover edge cases between f1f2f3f4f5=00000 and f1f2f3f4f5=11111
32 possible Binary combinations for 5 digits
0   0   0   0   0   00000=0
0   0   0   0   1   00001=1
0   0   0   1   0   00010=2
0   0   0   1   1   00011=3
0   0   1   0   0   00100=4
0   0   1   0   1   00101=5
0   0   1   1   0   00110=6
0   0   1   1   1   00111=7
0   1   0   0   0   01000=8
0   1   0   0   1   01001=9
0   1   0   1   0   01010=10
0   1   0   1   1   01011=11
0   1   1   0   0   01100=12
0   1   1   0   1   01101=13
0   1   1   1   0   01110=14
0   1   1   1   1   01111=15
1   0   0   0   0   10000=16
1   0   0   0   1   10001=17
1   0   0   1   0   10010=18
1   0   0   1   1   10011=19
1   0   1   0   0   10100=20
1   0   1   0   1   10101=21
1   0   1   1   0   10110=22
1   0   1   1   1   10111=23
1   1   0   0   0   11000=24
1   1   0   0   1   11001=25
1   1   0   1   0   11010=26
1   1   0   1   1   11011=27
1   1   1   0   0   11100=28
1   1   1   0   1   11101=29
1   1   1   1   0   11110=30
1   1   1   1   1   11111=31
*/

rule "Calculate average grade when all frequencies are 0 f1f2f3f4f5=00000=0"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 == 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// dividing by zero
    	modify($rating) { 
    		 setAverageGrade((double)0);
    	}      
end

rule "Calculate average grade when f1f2f3f4f5=00001=1"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 == 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00010=2"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 == 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00011=3"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 == 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00100=4"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 != 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00101=5"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 != 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00110=6"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 != 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=00111=7"
    when
        $rating: Rating(frequency1 == 0 && frequency2 == 0 && frequency3 != 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01000=8"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 == 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01001=9"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 == 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01010=10"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 == 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01011=11"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 == 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01100=12"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 != 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01101=13"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 != 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01110=14"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 != 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=01111=15"
    when
        $rating: Rating(frequency1 == 0 && frequency2 != 0 && frequency3 != 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10000=16"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 == 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10001=17"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 == 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10010=18"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 == 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10011=19"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 == 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10100=20"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 != 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10101=21"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 != 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10110=22"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 != 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=10111=23"
    when
        $rating: Rating(frequency1 != 0 && frequency2 == 0 && frequency3 != 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11000=24"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 == 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11001=25"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 == 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11010=26"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 == 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11011=27"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 == 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11100=28"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 != 0 && frequency4 == 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11101=29"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 != 0 && frequency4 == 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when f1f2f3f4f5=11110=30"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 != 0 && frequency4 != 0 && frequency5 == 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	} 
end

rule "Calculate average grade when all frequencies are not 0 f1f2f3f4f5=11111=31"
    when
        $rating: Rating(frequency1 != 0 && frequency2 != 0 && frequency3 != 0 && frequency4 != 0 && frequency5 != 0)
    then
    	// weighted average = sum(grade * grade frequency)/total number of grades
    	modify($rating) { 
    		 setAverageGrade((double)(1*$rating.getFrequency1()+2*$rating.getFrequency2()+3*$rating.getFrequency3()+4*$rating.getFrequency4()+5*$rating.getFrequency5())/($rating.getFrequency1()+$rating.getFrequency2()+$rating.getFrequency3()+$rating.getFrequency4()+$rating.getFrequency5()));
    	}     
end

/*rule "Calculate like dislike ratio when all values are null"
    when
        $r: Rating(frequencyLike == null, frequencyDislike == null)
    then
    	// ratio = number of likes / (number of likes + number of dislikes)
    	modify($r) { 
    		setLikeDislikeRatio((double)0);
    	}
       
end

rule "Calculate like dislike ratio"
    when
        $r: Rating(frequencyLike != null, frequencyDislike != null)
    then
    	// ratio = number of likes / (number of likes + number of dislikes)
    	modify($r) { 
    		setLikeDislikeRatio((double)$r.getFrequencyLike()/($r.getFrequencyLike()+$r.getFrequencyDislike()));
    	}
       
end*/

